# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: 곽민창 (Kwark Min Chang)
title: 3rd Grade University Student
email: kwarkmc@naver.com
website: https://github.com/kwarkmc

# Social links
github_username: kwarkmc
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: min__dow
#linkedin_username: 준현-이-043767168
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  나이 : 23 세 (1999년 생) 

  최종 학력 : 4년제 대학교 재학중 (한양대학교 ERICA 캠퍼스)

  사는 곳 : 경기도 동탄신도시


  병역사항 : 대한민국 공군 병장 만기전역 (2020.02.10 ~ 2021.11.13)

  사용 기술 : <mark>C</mark>, <mark>CPP</mark>, <mark>Python</mark>, <mark>Tensorflow2.0</mark>

  <mark>기계학습</mark> 개발자를 목표로 하고있습니다.

연락처 : 010 - 4138 - 3152

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# test Section
# test_title: test

# More Section
#more_title: 그 밖에 활동
#more_content: | # this will include new lines to allow paragraphs
#  - [개인 블로그](https://pro-dev.tistory.com/)

# Footer
footer_show_references: true

# Build settings
livereload: true

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
